{{- if .Values.webhook.enable }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: agentic-platform-mutating-webhook-configuration
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.certmanager.enable }}
    cert-manager.io/inject-ca-from: "{{ $.Release.Namespace }}/serving-cert"
    {{- end }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
webhooks:
  - name: mcomponent-v1alpha1.kb.io
    clientConfig:
      service:
        name: agentic-platform-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /mutate-kagenti-operator-dev-kagenti-operator-dev-v1alpha1-component
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions:
      - v1
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - kagenti.operator.dev
        apiVersions:
          - v1alpha1
        resources:
          - components
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: agentic-platform-validating-webhook-configuration
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.certmanager.enable }}
    cert-manager.io/inject-ca-from: "{{ $.Release.Namespace }}/serving-cert"
    {{- end }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
webhooks:
  - name: vcomponent-v1alpha1.kb.io
    clientConfig:
      service:
        name: agentic-platform-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-kagenti-operator-dev-kagenti-operator-dev-v1alpha1-component
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions:
      - v1
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - kagenti.operator.dev
        apiVersions:
          - v1alpha1
        resources:
          - components
{{- end }}
