apiVersion: v2
name: kagenti-beeai-operator-chart
description: A Helm chart to distribute the project kagenti-operator
type: application
version: 0.1.0
appVersion: "0.1.0"
icon: "https://example.com/icon.png"
